"""Add verification tables

Revision ID: 950ed626b989
Revises: b0f819beba06
Create Date: 2026-01-07 09:52:16.273203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950ed626b989'
down_revision = 'b0f819beba06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index('idx_composite_search')
        batch_op.drop_index('idx_id_number')
        batch_op.drop_index('idx_member_number')
        batch_op.drop_index('idx_name')
        batch_op.create_index(batch_op.f('ix_members_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_member_number'), ['member_number'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_member_number'))
        batch_op.drop_index(batch_op.f('ix_members_id_number'))
        batch_op.create_index('idx_name', ['name'], unique=False)
        batch_op.create_index('idx_member_number', ['member_number'], unique=False)
        batch_op.create_index('idx_id_number', ['id_number'], unique=False)
        batch_op.create_index('idx_composite_search', ['member_number', 'id_number'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
