"""Initial migration

Revision ID: da383495ca70
Revises: 
Create Date: 2026-01-08 11:06:03.935148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da383495ca70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('idx_composite_search')
        batch_op.drop_index('idx_id_number')
        batch_op.drop_index('idx_member_number')
        batch_op.drop_index('idx_name')

    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_search_logs_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.create_index('idx_search_logs_date', ['searched_at'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('idx_name', ['name'], unique=False)
        batch_op.create_index('idx_member_number', ['member_number'], unique=False)
        batch_op.create_index('idx_id_number', ['id_number'], unique=False)
        batch_op.create_index('idx_composite_search', ['member_number', 'id_number'], unique=False)

    # ### end Alembic commands ###
